# Generated by Django 3.2.4 on 2021-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_alter_subscribedusers_yes_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('yes_no', models.BooleanField(default=False)),
            ],
        ),
    ]
