# Generated by Django 3.2.4 on 2021-11-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0004_register_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_me',
        ),
        migrations.RenameField(
            model_name='subscribedusers',
            old_name='name',
            new_name='password',
        ),
    ]
