# Generated by Django 3.2.4 on 2021-11-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0005_auto_20211120_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='yes_no',
            field=models.BooleanField(blank=True, default=False, max_length=5),
        ),
    ]
