# Generated by Django 3.2.4 on 2021-11-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0006_alter_subscribedusers_yes_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='yes_no',
            field=models.BooleanField(blank=True, default=False, max_length=5, null=True),
        ),
    ]
