# Generated by Django 3.2.4 on 2021-11-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0008_alter_subscribedusers_yes_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='yes_no',
            field=models.BooleanField(null=True),
        ),
    ]
