# Generated by Django 3.2.4 on 2021-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0009_alter_subscribedusers_yes_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='yes_no',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
